### ISSUE TITLE
Support for a newbie

### ISSUE THREAD

**Issue by mitchelljohnson19** [aaronpk/Overland-iOS#104]
Hello,

Hope you can help. I am very new to this but am developing a basic dispatch system using Filemaker. 

Your solution is exactly what I need to track iOS devices, im okay working with an API but im a bit lost of how or where I can host the data to pull it using an API.

Can you suggest a simple server set up of where I can host the data to be able to then pull it using an API request?

Many Thanks

**Comment by mdav43** [comment]
I'm put together own server to record the data from the mobile app.

I used the following very simple Python script as the server.
https://gist.github.com/mdav43/960fddcae61288e10c0abd6d69f65915

I run this on a raspberry pi I have. If you're running on a mac or pc, just remove the journal logging.

End result, this will store geojson files just in the current working directory.

I haven't got around to visualising the data yet. I might just cheat and convert to gpx format and import into another app - like "Quantified" on ios.

An additional step, to ensure you don't have to manually run the server every time you want to move data from the app to your server/pc is to setup the python script to run forever as a service. If your running on linux, you can also follow these instructions. https://gist.github.com/funzoneq/737cd5316e525c388d51877fb7f542de#gistcomment-2306584

**Comment by mdav43** [comment]
Further to the above, I created a simple setup to view the output of overland app - a temporary solution whilst I develop something else more suitable.

1. Setup the server above
2. Run the following command to combine multiple geojson files into one (https://gist.github.com/mdav43/e81298a5fb6c0c53614df41953715648)
3. I use Rstudio to view the raw data - Markdown file here: https://gist.github.com/mdav43/e4c39206f9892dc05e349d836cd0be96

**Comment by aaronpk** [comment]
You can try using Open Humans to host the data and pull from there https://overland.openhumans.org/
