### ISSUE TITLE
Recovery from loss of phone charge

### ISSUE THREAD

**Issue by jeremycherfas** [aaronpk/Overland-iOS#106]
I had some mysterious trouble a while ago with Overland recording very few points during the day. I may now have got to the bottom of the problem.

A couple of days ago, I was unable to recharge my phone, which switched itself off. The following day, Overland once again recorded very few points during the day.

When I noticed, a couple of days later, I quit and restarted and location recording resumed correctly.

Is it possible that before the phone runs completely out of charge, Overland goes into some power-saving mode from which it does not recover when the charge is restored?

I plan to let the phone run out of power again today to test.

**Comment by jeremycherfas** [comment]
In addition, updating iOS had the same effect.

**Comment by aaronpk** [comment]
This is super weird, but as far as I know there's nothing I can do to change this behavior. I'm going to close this since there's no action to take, but it will be searchable if this happens again or if anyone knows of a solution that an app can do to solve this.
