### ISSUE TITLE
more trip-mode labels

### ISSUE THREAD

**Issue by sebsel** [aaronpk/Overland-iOS#11]
I found myself short of a mode for 'tram' and/or 'metro', which are distinct trip modes for me. In a chat, you mentioned 'boat'. So here are some:

- tram
- metro
- boat

I could come up with some more (skateboard, shared bikes), but maybe nicer to add them by three.

The nicest thing would be to make an option to add custom ones, but with the icons, that would be a lot of UI.

**Comment by sebsel** [comment]
The names seem to give some localization issues. 'Tram' is what is described on https://en.wikipedia.org/wiki/Tram and 'Metro' is what is described on https://en.wikipedia.org/wiki/Rapid_transit
@aaronpk used 'train' for both, but I like to make the distinction between those based on public transport in The Netherlands.

There might also be room of a 'Lightrail' option, kind of in between 'tram' and 'metro'. 

For comparison: the list of transport types in the Moves app is: Airplane, Boat, Bus, Car, Escalator, Ferry, Funicular, Motorcycle, Sailing, Scooter, Train, Tram, Underground.
From Strava: Ride, Run, Swim, Hike, Walk, AlpineSki, BackcountrySki, Canoeing, Crossfit, EBikeRide, Elliptical, IceSkate, InlineSkate, Kayaking, Kitesurf, NordicSki, RockClimbing, RollerSki, Rowing, Snowboard, Snowshoe, StairStepper, StandUpPaddling, Surfing, VirtualRide, WeightTraining, Windsurf, Workout, Yoga

With the waterproof iPhone 7 there might be room for 'Swim'? Skateboard might make sense for some people too. But let's not add things just for the adding of things.

**Comment by aaronpk** [comment]
I suppose the real solution here is to let people add their own icons and labels in the settings. It could even search thenounproject.com for icons! That's a bigger project than I can handle though, despite having written this app I'm not really an iOS developer.

**Comment by EdwardHinkle** [comment]
That's a good idea to let people add their own icons and labels. Maybe we can rename this issue to "Add custom trip modes" or close this issue and open a new one with that title linking to this one? I think the title doesn't reflect the current status of the issue. It's either fixed because of the tram, metro and boat being added in #12 or it's still open because we want to add custom modes.

**Comment by aaronpk** [comment]
Closing this issue since tram, metro and boat were added in #12! We can open a new issue for adding the ability for the user to add custom modes if someone wants.
