### ISSUE TITLE
Device ID does not save on Android Apps

### ISSUE THREAD

**Issue by wildernessfamily** [aaronpk/Overland-iOS#116]
First, I wanna say amazing job. Love this app.
I have it on my iOS devices including my iPad. Works great.
I'm using it with NextCloud PhoneTrack App.

I downloaded the Android version for my LG phone.
NextCloud PhoneTrack app provides the post URL:
https://NEXTCLOUD_URL/apps/phonetrack/log/opengts/SECRET_TOKEN/yourname
For "YourName" I name the device. It works a few times but then after maybe the fifth or sixth post it changes to undefinded.
I try to place the name in the Device ID field (Optional). That works. However, when I exit the app and come back into the app the name is missing. It doesn't save the Device ID when leaving the app.

If you need screenshots etc. Just let me know.
Thanks again for an awesome app.

**Comment by aaronpk** [comment]
Thanks! You'll need to open an issue on the Android version, it's completely separate and maintained by someone else.

https://github.com/OpenHumans/overland_android
