### ISSUE TITLE
Add a phone identifier?

### ISSUE THREAD

**Issue by ipearx** [aaronpk/Overland-iOS#118]
Hi I'm working on a new tracking map website that allows multiple people to share their location on the same map. The problem I've got is Overland doesn't seem to give any actual device ID at all. Only what the user configures as 'device ID'.

The problem comes if 2 people enter the same 'device ID', there's no way to identify that the devices are not the same device. For example if someone uses "TIM" as the device ID, and then someone else over the other side of the world uses "TIM", both person's location would jump from one position to the next constantly as data comes in.

I could get around this by issuing people a device ID they have to use, but that makes life trickier for the end user. What I'd like to do is use the app's 'device ID' field as a label of the users choosing. And have an actual device ID to identify devices apart from each other.

Now for privacy reasons, you can't get the iPhone's device ID any more, but Apple has allowed a similar ID that is unique to a 'developer' on that particular device. Perfectly good for my purposes. Read how to get it here for swift at least:
https://stackoverflow.com/questions/25925481/how-to-get-a-unique-device-id-in-swift

It would be very handy if that developer/device ID was available in the API data sent. 
Cheers!

**Comment by ipearx** [comment]
Thanks for implementing!

**Comment by aaronpk** [comment]
Cool! I just added a link to your site to the readme too!
