### ISSUE TITLE
Feature Request: Multiple Endpoints

### ISSUE THREAD

**Issue by sillygwailo** [aaronpk/Overland-iOS#120]
I'd like to set up multiple (maybe with a reasonable limit of, say, 5) URL endpoints so that it can ping multiple apps at once. That's mostly because I want to use my own endpoint (I made a "Which Toronto Neighbourhood Am I In? endpoint) but also ping Open Humans, for example.

**Comment by aaronpk** [comment]
hmm, I don't think that would be a good idea, it would significantly complicate how the app handles things. For example, if it fails to upload a batch to one of the 5 endpoints, what should it do with that data? A better approach would be to create a proxy endpoint that the app uploads to and you can have that endpoint send the data around elsewhere. That's actually what I do as well, the app pushes everything to [Compass](https://github.com/aaronpk/Compass) and I have a few webhooks configured there that notify other services such as my Home Assistant instance.
