### ISSUE TITLE
Configure wifi zones UX

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/Overland-iOS#133]
> Hey @aaronpk, already enjoying this new update! Im testing it on TestFlight. Is this the best place for feedback?

> The new time and distance filters are great, and the dark mode support. I have a question about the Configure Wifi Zone thing. The first time I clicked it, it said it registered my home wifi as the zone and set the long/lat. However, Im at work now and wanted to set another wifi zone. I clicked configure again but there wasnt much of a UI response and the old wifi name was automatically populated in the form. So its unclear so far if I can set multiple wifi zones, or where my current zone is configured. Anything Im missing here to make it more clear? Thanks!

_Originally posted by @momonala in https://github.com/aaronpk/Overland-iOS/issues/41#issuecomment-1809851236_

**Comment by aaronpk** [comment]
Yeah the wifi zone thing is a bit of a hack, and I'm definitely not good at UI stuff on iOS.

Right now there can be only one wifi zone configured.

The way it works is the first time you click it, it will prefill the location and wifi name and you'll see "Save" and "Cancel". If you already have a wifi zone configured, the buttons will say "Save" and "Clear".

This definitely needs some improvement, and I'd also like to be able to set more than one. That is all going to take a significant amount of coding though, and in particular the kind of iOS coding that I am not good at!

**Comment by momonala** [comment]
Got it, this makes sense now and I can replicate that reset behavior. Thanks for the clarification. 

Im a data engineer by day, and I only just started to get tinkering in iOS development. But now that I can build the project in XCode and deploy it to my phone, maybe Ill try playing around with it one of these weekends and see if I can contribute anything valuable. Thanks!

**Comment by aaronpk** [comment]
That would be amazing! 

This guide is probably what we should use for this, creating a collection that has a bunch of list items in it. If you skim through this you'll quickly see why I am a bit overwhelmed 😅 

https://developer.apple.com/tutorials/app-dev-training/creating-a-list-view
