### ISSUE TITLE
Significant locations not logged in standard mode in 1.3

### ISSUE THREAD

**Issue by dontic** [aaronpk/Overland-iOS#135]
Relates to #41 

Been testing the beta app in ios 17.1.1 and the new functionalities are great.

One thing I have noticed is that I'm not getting significant locations anymore at my endpoint. While I do want to track my precise location as best as possible, it was quite useful to also get the significant locations at the same time. Thus, having a separate setting for the later was convenient.

I imagine this is because of the new settings which only let you choose one or the other but I might be wrong:
## Old settings
![image](https://github.com/aaronpk/Overland-iOS/assets/25914304/ce012928-17e9-47d3-9da4-1cf1f042b78c)

## New settings
![image](https://github.com/aaronpk/Overland-iOS/assets/25914304/be3124fe-9969-406e-8297-cd865f8d66cd)

If this is the case, would it be possible to add a "middle" option for `standard+significant` or `both`?

**Comment by dontic** [comment]
@aaronpk I've been testing this after the update. I've stopped receiving significant locations, right now I'm not sure if it's the app or if something change in ios and they've renamed "arrival_date" to a different string so my backend is not processing it correctly anymore

I'll investigate this further when I have a bit more time

**Comment by dontic** [comment]
I got super confused there. Thought `significant locations = visits`. It's well documented in the readme 🤦🏻‍♂️

As for including the setting in the app, I personally leave it always on. I have a different table on my database for visits, which I then visualize on a different map plot (this has proven often even more useful for me than the trips):

![image](https://github.com/aaronpk/Overland-iOS/assets/25914304/1d286f8e-2624-4c29-879d-f2e10b0ae2a9)

It can be useful to give the option of track visits and metadata separately though, if that's even possible. There might be people that might want to get metadata without visits or viceversa, but not really sure how many are there to make it worth it.

Thanks for the nice insights!

**Comment by aaronpk** [comment]
Ok cool well I'm convinced that visit-only tracking is something people might want, so I'll work on that.

> It's well documented in the readme

Where are you seeing that?

**Comment by aaronpk** [comment]
Turns out there has been an open issue for visit-only tracking from years ago, so we'll continue the visit-only feature discussion there: #31

**Comment by aaronpk** [comment]
Oh sorry I misunderstood, I thought you were saying that "significant location = visits" was documented in the README and I was looking for where to fix it!

I'm excited that you have had good luck with the Visits feature, and that's a great map! All the more motivation for me to polish that off a bit.

**Comment by lostfocus** [comment]
And thanks for the inspiration - I don't do anything with my `visits` data, yet but that map is a cool idea!
