### ISSUE TITLE
Timestamp per point

### ISSUE THREAD

**Issue by kwando** [aaronpk/Overland-iOS#137]
Is there a way to get a timestamp associated with each point/position?

Im looking into easy options for tracking our sailing boats during our weekly races and this app does almost everything we need for that, but I think we would need the timestamp per point for that to work.

Is this something that could be added? I assume the HTTP payload format needs to change in that case though.

Is this something you would consider adding? I never did any iOS coding but I would be willing to give it a shot, 

Best Regards,
Hannes N

**Comment by momonala** [comment]
Each GPS point contains the timestamp in the geojson payload, right? See here for the HTTP response: 
```
POST /api HTTP/1.1
Authorization: Bearer xxxxxx
Content-Type: application/json

{
  "locations": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -122.030581, 
          37.331800
        ]
      },
      "properties": {
        "timestamp": "2015-10-01T08:00:00-0700",
...
```
https://github.com/aaronpk/Overland-iOS#api

**Comment by kwando** [comment]
Yes you are completely right. I don't see how could miss that! 
I'll start to implement a server prototype then  :)

Sorry for the noise, Have a great weekend :)
