### ISSUE TITLE
Some ideas to improve wifi zones

### ISSUE THREAD

**Issue by AIP21** [aaronpk/Overland-iOS#147]
The new update is fantastic, it adds a lot more functionality and configurability to the app.

I have some ideas on how the wifi zones could be improved.

- [ ] The ability to add multiple wifi zones would be really helpful if you don't want noisy data when at home and at school/work.

- [ ] Allow the user to instead use an IP address instead of a network name. This could be made even better if it could differentiate between different access points, which would make it more useful on a campus with multiple buildings on the same network (I am pretty sure this could be done by differebtiating betwene IP addresses).

- [ ] Make the app send a notification when the device connects to a new WiFi network, asking if the user would like to add a new WiFi zone. Tapping on the notification would automatically add a new WiFi zone using the currently connected wifi network and the current location. This could also include an option to bypass notifications and just always automatically add WiFi zones when connecting to a new WiFi network.

**Comment by lalzart** [comment]
How do you configure the WiFi zones? Is it within the app's UI?

**Comment by aaronpk** [comment]
@lalzart Yes, it's in the settings screen. It's definitely a barebones feature right now.

@AIP21 Thanks for the ideas! I would definitely like to add support for multiple wifi zones. We do get access to the mac address of the wifi hotspot which would give you the more granular location data than just wifi name on a campus. I'm going to split this out into separate issues to track:

#151 #152
