### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by naibed2000** [aaronpk/Overland-iOS#153]
Hello,
Been using the test app for a while now. Seems to be working really good. Except for 2 issues :
- if i restart my phone the app is not loaded. This was not the case in iOS16. I don't know if it's an issue with iOS17 or overland. I believe other background app gets restarted.
- The app crashes from time to time. I would love to help give logs or debugs. But i haven't figured out how/when this happens. Though when it happens, the "visits" seems to still be logged.
Thanks

**Comment by aaronpk** [comment]
Can you double check you're running the latest beta? I did push an update out about 5 days ago that should have fixed the crashes.

I am not sure what's going on with restarting the phone, but it very likely will depend on what settings you have enabled as to whether the app is resumed on restart.

**Comment by naibed2000** [comment]
hi,
- i'm running 1.3(2024042717)
- If i restart my phone, for example Traccar Client starts up alone and starts updating location but overland does not. Not sure where/what settings to change.
- Thanks

**Comment by aaronpk** [comment]
Try turning on the "significant location" feature, that should get the OS to re-launch the app when the phone restarts.

**Comment by naibed2000** [comment]
seems like it helps after phone restarts. Will report back if it helps about crashes.
