### ISSUE TITLE
What are the best settings for tracking?

### ISSUE THREAD

**Issue by getwet** [aaronpk/Overland-iOS#157]
Hi Folks,

this is not a bug. On the last version I had some good settings with significant only, but after the update I can't find the correct settings and my tracks looks like this, which was not my way:
![image](https://github.com/aaronpk/Overland-iOS/assets/5207915/345567fb-658b-493f-827d-ac84f3a51127)

My settings are:
![image](https://github.com/aaronpk/Overland-iOS/assets/5207915/d8eabf28-8460-4474-b6a5-ad8a3d73aac0)

![image](https://github.com/aaronpk/Overland-iOS/assets/5207915/950f1b98-3e0c-4446-91f8-21d3de902452)

![image](https://github.com/aaronpk/Overland-iOS/assets/5207915/ed0c2b85-dd13-4154-9f6b-69dd8efa0ee0)

On my iOS GPS settings I use Always. 

Can someone give me a good recommendation to improve my tracks?

Many thanks

**Comment by getwet** [comment]
I closed the ticket, because I switch to Traccar. It works out of the box.

**Comment by momonala** [comment]
Looks like you set the desired accuracy to within 100m, not "best". The tracks you provide seem to show about 100m variance. "Best" gives about 1-3m accuracy for me and works out of the box.
