### ISSUE TITLE
[Feature Request] Add ability to set trigger interval - (To reduce battery usage)

### ISSUE THREAD

**Issue by radh21301** [aaronpk/Overland-iOS#160]
Right now, I am not sure if the Overland app has a trigger that request the OS to get a GPS reading. I might not be understanding how the software actually works.

I think it would be a great option to set trigger based on time. If we use something like distance, the GPS needs to be always on to determine if we traversed that distance. I suppose if we used time interval as a trigger, it would mean that the GPS could be turned off for a certain duration? It would definitely depend on the value of that interval - if it is too short (say a few seconds), then the GPS would still be continuously on. But if it is say 10 mins, the GPS will be turned off right?

I saw this suggestion on the 'Traccar' app forums (this is an app I currently use). The settings available in Traccar is way limited compared to Overland (added a screenshot to show what is has), but the battery usage is minimal which is a huge plus - currently I have set it to get a GPS location every 5 mins.

References:
https://www.traccar.org/forums/topic/optimum-settings-for-performance-and-battery-usage/
https://www.traccar.org/forums/topic/battery-drainage-issue-with-traccar-client/
Project repo: https://github.com/traccar/traccar

<img width="754" alt="image" src="https://github.com/aaronpk/Overland-iOS/assets/45341381/4edd5a08-279f-4021-8794-994ce58f5bad">

**Comment by aaronpk** [comment]
Location services in iOS don't work the way you think. There isn't a way to tell the OS to trigger location updates at a specific interval, it's a lot more complicated than that. There also isn't explicit on/off control of the GPS chip on the phone, the OS is managing the underlying hardware. Please thoroughly read the settings section in the readme for an explanation of all the settings in the app:

https://github.com/aaronpk/Overland-iOS?tab=readme-ov-file#settings

All of the settings available to app developers are exposed in the Overland settings, so you can certainly configure it to reduce battery usage if you want.
