### ISSUE TITLE
Adding server URL fails

### ISSUE THREAD

**Issue by HStep20** [aaronpk/Overland-iOS#161]
Currently testing out DaWarich (open source Google Timeline that supports this) and for some reason the app is not accepting my url as a valid server endpoint. 

DaWarich instructs to use a url in this format :  http://URL-OF-SERVER/api/v1/overland/batches?api_key=XXXXXX, but when I put that into the server config section, it just turns red and doesn't save. 

No indication of what's going on for troubleshooting, but I've tried adding the api key to the separate box as well and same issue. Does it only support HTTPS connections?

**Comment by aaronpk** [comment]
It should allow you to enter an http URL too. I just tested and I'm able to save an http URL like the above. Maybe there's an extra space at the beginning or end of what you're entering, so that it's not a valid URL?

**Comment by HStep20** [comment]
Im still not sure why it was doing that. I was on the road to the airport, VPNd in to my local network where I could reach the page via the browser, so perhaps that was interfering. I tried again yesterday, and its now working properly. Much better UX/reliability than OwnTracks from my experience, so thank you!
