### ISSUE TITLE
certificate

### ISSUE THREAD

**Issue by Joe-ncB** [aaronpk/Overland-iOS#162]
Hi,
I'm testing Overland on iOS and my own server (nextcloud)
I'm using a self signed certificate.
When I try to transfer the data i get the notification that i use a unsafe certificate to the server xxx (my server)
Of course, it is a self signed one ... but i know the server -- and i want to transfer on my own risk ........

what i am missing is a OK-button where i can confirm that i want to proceed with the transfer
With browsers and certain other apps there is this possibility.

Is there a way i can manage that with Overland too ??
If not, is there a possibility to get it implemented ?
or am i totally blind for not finding it in the prefs

hopfully someone can help

Regards Joe

**Comment by aaronpk** [comment]
There is no way to disable the certificate check in the app.

I would recommend using Letsencrypt to get a free certificate. Or if you want to, you can create your own CA and install your root certificate in your phone so that it trusts your own issued certs.
