### ISSUE TITLE
App attaching 'cycling' tag to 'monorail' events

### ISSUE THREAD

**Issue by gloriouslyawkwardlife** [aaronpk/Overland-iOS#168]
Had a little fun last night using Overland to track myself around Walt Disney World. When I selected the 'monorail' tag for trip tracking, it pushed the data out using the 'cycling' tag instead and I had to correct it at the destination database. The two options on the Trip Mode screen are nowhere near each other, so it can't be a matter of 'fat-fingering' the wrong option.

This is on iPhone 16 Pro Max running iOS 18.0.1.

![IMG_2225](https://github.com/user-attachments/assets/6848d2d7-18d2-4d41-a75b-bd0030f7a495)

**Comment by gloriouslyawkwardlife** [comment]
For the curious:

![routes](https://github.com/user-attachments/assets/07a286c3-6e62-40e5-b3d5-0f345aeb6461)

**Comment by gloriouslyawkwardlife** [comment]
Aaron,

I would have chosen the selection, tapped “Start” back at the main screen to start the track, and _then_ switched off to another app if need be; come back and tapped “Stop” on the main screen when the segment is done.

SB

**Comment by gloriouslyawkwardlife** [comment]
I would default it to Null (or a blank value) rather than a potentially wrong one. I do see a lot of my data coming out as blank activities when I haven't explicitly selected a mode. I already have Swarm for checkins and Bouncie.com for driving trips, so this fills in the remaining gap (other than constantly recording workouts on Apple Watch :-) ). 

Thanks for the app!

**Comment by gloriouslyawkwardlife** [comment]
Hey Aaron,

It did it again, this time for 'tram'. 

![Unknown](https://github.com/user-attachments/assets/eb4b8e6d-7a90-4fd6-93e0-4e8d16f08d79)

**Comment by aaronpk** [comment]
This is very strange, I've been using this app for literally years and this has never once happened before. How are you reading the trip mode on the server?

**Comment by gloriouslyawkwardlife** [comment]
Now I'm wondering if it could be my cgi script.  I'll start pushing this to my CouchDB instead for a while (it takes the JSON from the app as-is) and see if things change.

**Comment by gloriouslyawkwardlife** [comment]
Another example. The red markers in the middle of the lagoon should have been recorded as 'boat' but the motion value sent was an empty array `[]`.

<img width="945" alt="Unknown" src="https://github.com/user-attachments/assets/8e559246-c52d-4fb4-8fd4-19abeab1ce77">

**Comment by aaronpk** [comment]
ohhhhhh now I see. The "motion" values recorded with the individual points are from iOS, not from the trip mode setting. Under the mph number on the main screen you'll see this text change from blank (unknown) to "stationary", "cycling", "driving", etc. These are provided by the OS along with the position. This is entirely separate from the Overland trip mode setting.

**Comment by gloriouslyawkwardlife** [comment]
That explains a lot. :-)  I enabled the advanced data in the app settings and I now see where the information appears as `$.properties.mode` on certain JSON payloads; a bit more complicated than I expected.  I don't have a web server handy where I can install the compass endpoint and have been trying to figure it out with Python and Wolfram Language.

**Comment by aaronpk** [comment]
Thanks, it's not a bad idea for it to work the way you thought, so I created an issue to track that new feature: #170

**Comment by gloriouslyawkwardlife** [comment]
I ultimately ended up finding and switching to a [Garmin Etrex SE](https://www.garmin.com/en-US/p/835742) at a discount that I can clip onto my person or the backpack I'm just about everywhere with and will log once per second for several days on a pair of "AA" batteries (I have quick-rechargeables) and sync with Garmin Connect on my phone over BTLE, saving each segment with an attached activity. I really do like where the Overland app is going, though. 

Example Embed: <https://connect.garmin.com/modern/activity/embed/17545970606>

**Comment by aaronpk** [comment]
wow that's a cool looking device! I'm curious how it'll work for you long term. The major limitation i see is that it is only GPS positioning, whereas the iPhone uses wifi to supplement GPS as well, which makes it work a lot better in certain environments. For plain outdoor stuff with a clear view of the sky, GPS is good enough though.

**Comment by gloriouslyawkwardlife** [comment]
This pulls in GPS, GLONASS, Galileo, QZSS, and Beidou and I've actually got it running now inside my apartment with an accuracy of 10 ft. Vast improvement over the previous units I've had.
