### ISSUE TITLE
Didn't know that result:ok is required in JSON response for sending location.

### ISSUE THREAD

**Issue by p13i** [aaronpk/Overland-iOS#174]
Can we document that `{"result": "ok"}` is required in the response to make it a valid response?

https://github.com/aaronpk/Overland-iOS/blob/5f2a5be9bdea8a26677a37f15f477360613c5500/GPSLogger/GLManager.m#L236C43-L236C58

Happy to start on the code; I'd like to add it to the UI or README, somewhere obvious.

Amazing app. Thanks <3

**Comment by aaronpk** [comment]
It's mentioned [in the readme](https://github.com/aaronpk/Overland-iOS?tab=readme-ov-file#system-settings) but it could be in a better spot. Feel free to suggest something in a PR.

**Comment by p13i** [comment]
Taking another look, your docs are already great, I just missed it earlier.
