### ISSUE TITLE
add option for "visit-only" tracking

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/Overland-iOS#31]
This app is already using the "visits" feature of iOS, but only as a supplement to standard "track" based tracking.

Apple provides a "visit" feature which allows the app to use almost no battery power, but it only registers a location update when you've stopped moving and have settled somewhere for about 10 minutes.

Adding an option for "visits" only would allow extremely battery efficient passive tracking, at the expense of losing the track data between points. However there are still plenty of use cases for tracking only visits. 

Please chime in or thumbs up here if this is something you'd be interested in using!

**Comment by oleg131** [comment]
I think "visits" tracking is very useful. I was gonna use Overland to track my location but even "significant locations" are too redundant for me - it would report a new location every few seconds even if I'm not moving. Using "visits" API would take care of filtering redundancy - both when locations are too close to each other and when the location changes too fast (e.g. when in a car).

**Comment by oleg131** [comment]
Does this mean that the app is already sending visits locations even if "standard" and "significant" are turned off?

https://github.com/aaronpk/Overland-iOS/blob/59c8d1d88ecf89733f7529ef9cc0a1ea38f67c90/GPSLogger/GLManager.m#L408

**Comment by aaronpk** [comment]
No, that method call is inside the `enableTracking` method. So it is always monitoring visits when tracking is enabled. When tracking is turned off, it calls `stopMonitoringVisits`.
