### ISSUE TITLE
Can't send information to Compass (500 internal server error)

### ISSUE THREAD

**Issue by veer0318** [aaronpk/Overland-iOS#33]
Not sure if this rep is the right one as it could also be an error of Compass. Nonetheless, here goes. So I installed Compass on my server and Overland on my iPhone. So far so good, I have about a thousand queued locations and tried (manually via "Send Now") to send the locations to my Compass installation.

There it goes wrong. I get a 500 internal server error, content type unacceptable. See attachment.
![33059](https://user-images.githubusercontent.com/8401159/31457746-094e4d28-aebe-11e7-916b-a87f856697ab.jpg)
(did some editing to hide private info)

Don't know what's going on. I can't find anything in my Apache error logs (I do see a request in my access log).

**Comment by aaronpk** [comment]
This means Compass isn't set up right, the app is getting a 500 server error so it's keeping the data and will try sending it again. I've made an issue to improve the docs for Compass, and also started that. Let's continue the conversation over there: https://github.com/aaronpk/Compass/issues/12
