### ISSUE TITLE
Update trip data format

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/Overland-iOS#43]
Include the full start/stop location record instead of just the coordinates.

**Comment by lostfocus** [comment]
I've seen this and the Compass ticket - is it now necessary to update the Compass instance when this update goes live or is it backwards compatible?

**Comment by aaronpk** [comment]
It's mostly backwards-compatible. The old Compass will still register a trip record so you shouldn't notice anything different really. Overland improved how it handles registering where a trip started, and that's the part that won't be recognized by an old version of Compass.

**Comment by lostfocus** [comment]
Okay, thanks. 👍
