### ISSUE TITLE
Auto send?

### ISSUE THREAD

**Issue by keepcarlson** [aaronpk/Overland-iOS#46]
Is there a way to have the data sent to the receiver endpoint without having to manually press the Send Now icon?  Even if I set the points to send in batch to fifty, and start, nothing goes to my receiver endpoint until I press the Send Now icon.  Knowing about battery drain, I am interested in live, real time tracking without user interaction.

**Comment by aaronpk** [comment]
The "send interval" slider selects how often the phone will send data to the server automatically. You can set that to a few options between 1 second and 30 minutes. The more often it sends the faster the battery will drain.

The app will send to the server when it gets a new location after the selected amount of time has passed since the last send. You can watch the "last sent" label to see this.

**Comment by keepcarlson** [comment]
Thanks for writing back so soon....
Hmmm I have the send interval slider set to 1 second. 
On the settings page, I have the following in order:
Enabled 
Other
Best
Never
50
Pause set to off
Resume set to off
Enable notifications set to on

Queued locations never clears and is now at 40,941
The Last Sent never changes from n/a even after I press Send Now.
Although I can see the data coming in on my server when I press Send Now.  So I know there is communication.

Doing something wrong, just not sure what?  
Thank you!

**Comment by aaronpk** [comment]
In that case it's likely that your server is not sending back the acknowledgement that the data was received. The app will hold on to the data until the server says "ok".

https://github.com/aaronpk/Overland-iOS#response

Once your server replies with that, the app will delete that set of queued locations.

**Comment by aaronpk** [comment]
That's a great question. Is there any way to configure what response the GeoEvent server sends to an HTTP request? I'm not really sure where to find documentation on it, a little bit of searching only turned up some tutorials that I couldn't really tell what they were for.

This is an interesting case, and I'm tempted to add a setting that will let you configure the app to accept any `HTTP 200` response as an "ok". That should work with GeoEvent server without any changes on the server then. Tho for myself, I still want the more strict check that the app currently does, so I'd want it to be a setting.

**Comment by keepcarlson** [comment]
I am using an input "connector" called rest-json-in which captures the incoming data from Overland (see inputfromoverland.png).  I've captured the incoming data as a .csv file (attached as zip).  The rest-json-in connector can be configured with certain parameters (restjsonin-properties.png) but I can't find one that seems to allow for sending back an "ok" response.  ESRI documentation is poor for how to configure these and/or explain what they do.
![inputfromoverland](https://user-images.githubusercontent.com/5710167/35650841-79deef9e-06ab-11e8-8910-8227d8172fca.png)
[output2018-01-31_12-53-38.zip](https://github.com/aaronpk/Overland-iOS/files/1683526/output2018-01-31_12-53-38.zip)
![restjsonin-properties](https://user-images.githubusercontent.com/5710167/35650874-9aeb9da4-06ab-11e8-900f-dc309b1be87e.png)

**Comment by aaronpk** [comment]
I've opened an issue to track this feature request. There will be a setting to enable treating any HTTP 200 response as a success: #55

**Comment by keepcarlson** [comment]
I have not been able to find this setting to treat any response as a success in the app.  Can you direct me to where I can find it?  I was looking for an "on" switch or something.  I am still unable to send locations to the custom URL.  Thank you.

**Comment by aaronpk** [comment]
Sorry, I haven't actually built this yet. I opened issue #55 to track the feature but haven't actually made any progress on it.
