### ISSUE TITLE
Add a setting that will disable "pause updates automatically" when in Trip Mode

### ISSUE THREAD

**Issue by EdwardHinkle** [aaronpk/Overland-iOS#48]
One thing I have found challenging is I almost always leave "Pause Updates Automatically" on, in order to save battery since I spend LARGE chunks of time in one location. Typically my house. The problem is when I am doing a trip (typically walking) and my movement is so slow that Apple determines that I am not moving. Apple then pauses the update automatically and my trip ends 👎 This makes me very sad when I'm trying to track a walk.

So my proposal is a setting that when activated:
1. When trip mode is activated, will check if "pause updates automatically" is on. If so, it will remember that, but temporarily disable that setting with iOS.
2. When trip mode is ended through clicking "stop", it will check if "pause updates automatically" had PREVIOUSLY been turned on before the trip began. If it was, then it should re-activate "Pause Updates Automatically" with iOS.

I don't know what you would call the setting but in essence it's "Don't pause updates during trips".

**Comment by aaronpk** [comment]
Great idea! I do think a setting for this is the right call since some people may want trips to end automatically still
