### ISSUE TITLE
Add configuration option to accept any HTTP 200 response as a success

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/Overland-iOS#55]
I like that the app is very strict about what it considers an acknowledgment that the server has received a batch of data. But there are some cases where you can't change the server's behavior. It would be useful to be able to switch into a mode where the app accepts any `HTTP 200` response as a success.

This would be a relatively uncommon setting, and not something that you'd change after setting it, so it should be either in the screen where you set up the endpoint URL, or could be buried in the iOS Settings app.

**Comment by sebsel** [comment]
fwiw: I have had a Compass server set up in the past. That address and token are still stored in my config, but the Compass server is down and returns a default Apache page with a 200 on that URL. If you would accept any HTTP 200, I would now have lost data.

(I think I have lost data. I should have cleared the API URL in the app before I went recording after such a long time.)

**Comment by aaronpk** [comment]
This will go out in the next release: #41
