### ISSUE TITLE
App crashes on open

### ISSUE THREAD

**Issue by EdwardHinkle** [aaronpk/Overland-iOS#59]
So i’m not sure if this is an issue with the app’s code or something about how I install and run it on my phone or my instance of compass.

Every couple of days Overland will crash while I’m the loading Storyboard. Once it starts I can’t get the app to load past the loading storyboard. The only way I can fix it is to rebuild the app in Xcode and re-run it on my device. Then it starts working again.

I’ve looked in Xcode’s devices panel at crash logs but I can’t find any crash logs connected to Overland. Finally, I can’t debug it because as soon as I have Xcode run the app on my device, it works again.

Hmmm maybe that’s the issue. Maybe Xcode is installing the debug version of the app on my device and it’s causing some type of issue and I should be doing the release build from Xcode for longer term installation?

Have you seen this at all?

(Originally posted at https://eddiehinkle.com/2018/03/12/2/reply/)

**Comment by lostfocus** [comment]
This is actually an Apple thing - every seven days apps stop working and need to be rebuilt. As far as I can remember it was the main reason Overland is in the app store: https://github.com/aaronpk/Overland-iOS/issues/13#issuecomment-329343269

**Comment by EdwardHinkle** [comment]
Oh wow! I didn’t even realize that!

**Comment by aaronpk** [comment]
It's an unfortunate side-effect of how Apple decided to implement the new free developer accounts! oh well!
