### ISSUE TITLE
Is the API documentation for version 1.2 (not yet in App Store)?

### ISSUE THREAD

**Issue by kurtishouser** [aaronpk/Overland-iOS#61]
I'm using Overland 1.1 and am currently working on an Express server (with plans for a React frontend) and I'm not seeing a separate `"trip"` object in the POST request as documented in the README. Instead I'm noticing an additional object in the `"locations"` array with a `"properties.type": "trip"` key/value anytime a trip is stopped.

The full object in the `"locations"` array looks like this:
```javascript
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
          -122.###...,
          37.###...
    ]
  },
  "properties": {
    "start": "2018-07-03T15:21:02Z",
    "end-coordinates": [
          -122.###...,
          37.###...
    ],
    "timestamp": "2018-07-03T15:21:10Z",
    "type": "trip",
    "stopped_automatically": false,
    "wifi": "myWiFi",
    "mode": "walking",
    "start-coordinates": [
          -122.###...,
          37.###...
    ],
    "end": "2018-07-03T15:21:10Z",
    "duration": 8.112072944641113,
    "distance": 13.436500415436331,
    "device_id": "",
    "steps": 0
  }
}
```
Thanks,

Kurtis

**Comment by aaronpk** [comment]
Yes, it looks like I added that in a change that is not yet in the app store version. I'm working on getting a new app store update ready though: https://github.com/aaronpk/Overland-iOS/milestone/3

**Comment by aaronpk** [comment]
Version 1.2 is published in the app store now!
