### ISSUE TITLE
Is launch by URL still used?

### ISSUE THREAD

**Issue by EdwardHinkle** [aaronpk/Overland-iOS#67]
I'm converting the App Delegate to Swift as there isn't much in it and there are a couple of things that need to be added to the App Delegate for the shortcuts stuff.

While converting, there was something I noticed here:
https://github.com/aaronpk/Overland-iOS/blob/f150bfcf87d8aec0b1d8a9cefb11c34ef7f18eb5/GPSLogger/AppDelegate.m#L63-L73

It seems that the app is set up for opening URLs but when I look at the actual project settings I don't see any URL schemes set up. Is this functionality actually used? I can put in the swift version but I don't know how to test it because I don't see an existing app url scheme.

**Comment by aaronpk** [comment]
I had configured a custom URL scheme to be able to launch the app and store an API endpoint from a URL. I was using this to quickly configure phones by sending a link via SMS. It's possible the custom URL scheme got lost at some point, but I'd like to restore the functionality.

**Comment by EdwardHinkle** [comment]
👍 sounds good. What was the custom url scheme, overland:// ?

**Comment by aaronpk** [comment]
Oh I think this existed before it was called Overland, but yeah let's go wth that!

**Comment by aaronpk** [comment]
This is fixed, and the endpoint, access token and device ID can all be set from the custom URL scheme now.
