### ISSUE TITLE
Rename Cocoapods Project to Overland?

### ISSUE THREAD

**Issue by EdwardHinkle** [aaronpk/Overland-iOS#69]
When initially getting this project to work on my local machine after the app was called Overland, leaving Cocoapods targeted at GPSLogger wouldn't let me build it. I'm wondering if it's because you already had the project built as GPSLogger so there is something cached in your system that allows it to continue working? So as I've been doing development on my side, my Cocoapods is targeted at Overland.

I'm guessing if anyone else wants to build or contribute to the project, it would require them to do the same.

https://github.com/aaronpk/Overland-iOS/blob/f150bfcf87d8aec0b1d8a9cefb11c34ef7f18eb5/Podfile#L4

**Comment by aaronpk** [comment]
Feel free to submit a fix! I don’t really know how cocoapods works, I am totally just winging this

**Comment by EdwardHinkle** [comment]
Sounds good. I’ve got the fix locally, I just didn’t want to push it if it was set up that way on purpose 👍
