### ISSUE TITLE
Suggest ending trip if still active while in one location

### ISSUE THREAD

**Issue by EdwardHinkle** [aaronpk/Overland-iOS#72]
If Apple suggests that the user has incurred a visit (by staying at this location for around 10 minutes) then we should send a local notification asking if the user would like to stop the trip

**Comment by aaronpk** [comment]
A notification is a good compromise here. Previously I was thinking about automatically ending a trip in this case, but I'm always worried about false positives, so a push notification suggestion with an easy to tap "confirm" would be great.

**Comment by EdwardHinkle** [comment]
Yeah, false positives are definitely an issue. For example: when running in circles along a path at a park. That happened to me when I use to have tracking automatically stop based on iOS settings.

Plus, it’s the same thing that watchOS 5 does, a notification with a confirm button and a cancel button.
