### ISSUE TITLE
Support sending access tokens in an HTTP header

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/Overland-iOS#73]
Currently you need to include a token in the URL that Overland sends to, which is not ideal for a number of reasons. It would be much better to include an access token in an HTTP header. This will require an additional config field on the endpoint settings screen.

* [x] Include new field for setting an access token in the settings screen
* [x] Send the access token in the HTTP `Authorization` header if set
* [x] Add the access token to the custom protocol launcher so it can be set when a config URL is launched from other apps

**Comment by gcs278** [comment]
I see that the source has been updated to reflect this, but the apple store's version of this app doesn't have this functionality. Is there a plan to get this update in the Apple Store?

I cloned and built the project to install it locally on my phone with xcode, but of course, Apple requires you to pay to use certain capabilities and I wasn't able to install on my phone with my "personal team" account. 

Just curios, no pressure. I understand you have to maintain a developer team account which costs money.
