### ISSUE TITLE
App crashing on submit.

### ISSUE THREAD

**Issue by motoservo** [aaronpk/Overland-iOS#74]
Trying to get this app and my API (Laravel app) to work together and after first getting a 500, then a 404, I think I finally got the end point right. But now it's just crashing every time I hit Send Now. I've rebooted, deleted the app and reinstalled, but same issue.

For troubleshooting this I just have the controller returning the array, with nothing else happening.

Have this coming as the response (according to my desktop app called HTTP Client, which is good for troubleshooting this kind stuff.)
["result","ok"]

Also have used the json() helper and it returns...
{"result":"ok"}

So, not sure why Overland is just crashing now. Please advise.

**Comment by motoservo** [comment]
Not sure what all I just changed in the prefs, but it's not crashing now. And seems to be working. :) I think the app needs a Purge Queue button, I had over 20K queued as I worked through the setup issues I was having. But glad to have the app, it was just what I need to show my customers where I am on the map (I'm a pedicabber in Santa Monica).

**Comment by aaronpk** [comment]
The app definitely shouldn't crash depending on the response from the server, so I'll leave this open to try to track down the cause. It seems like the first response `["result","ok"]` is likely the cause of the crash, so I'll try to reproduce that.

A "purge queue" button is a good idea!

**Comment by motoservo** [comment]
Took me a while to get my API setup right (I’ve been away from coding for a couple of years now) but now i’ve got it hitting my Laravel app and it’s working like a charm.

I’m setting up an app so my clients can follow me around Santa Monica (I’m a pedicabber and trying to start advertising on my cab). So, this was something I needed as my safari location script won’t work in the background (as you know) and you saved me from having to make this app myself.

Thanks!

**Comment by motoservo** [comment]
I do have a question. I’m able to get the top two (lat and lon), but the device_id line doesn’t seem to work.

'lat' => $request->input('locations.0.geometry.coordinates.1'),
'lon' => $request->input('locations.0.geometry.coordinates.0'),
'fleet_id' => $request->input('locations.0.properties.device_id’)

Do you see anything I’m missing about how I’m accessing the JSON?

**Comment by motoservo** [comment]
Never mind, I think I got it. While troubleshooting I somehow must have loaded up your app with some points using a higher device_id than I had available (it’s a foreign key). So, the inserts were failing. And with no way to see all that queued data I didn’t realize that old stuff was there, from before I had my local working.

More reason for that “Purge Queue”. ;)
