### ISSUE TITLE
Add JetBlue tracker as a data source

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/Overland-iOS#77]
see https://gist.github.com/dshanske/4d24893626a5ee2f9092cc55007bb271

**Comment by aaronpk** [comment]
https://gist.github.com/dshanske/2c1e09cdde3defc2753d957af3100d35

**Comment by dshanske** [comment]
https://gist.github.com/dshanske/71e366058f27f83e0cc0cd0b89942a22#file-gistfile1-txt

**Comment by aaronpk** [comment]
I've decided to drop this feature from the app as it's going to be too much work to maintain and would be better done as an external service anyway. I was noticing that the takeoff and landings would often not be recorded because the passenger wifi would be disabled below 10,000 feet anyway.
