### ISSUE TITLE
Support for Androidd

### ISSUE THREAD

**Issue by filips123** [aaronpk/Overland-iOS#80]
Can you make Android version of this app?

**Comment by aaronpk** [comment]
Unfortunately it's not as simple as just porting this to Android. Android handles things drastically differently, and shares nothing in common with iOS app development. There are several GPS trackers for Android already though! 

* [GPSLogger](https://gpslogger.app/)
* [Owntracks](https://play.google.com/store/apps/details?id=org.owntracks.android&hl=en)

**Comment by aaronpk** [comment]
There is now an Android version!

https://github.com/OpenHumans/overland_android
