### ISSUE TITLE
overland.p3k.app webpage shows incorrect json format for the api request

### ISSUE THREAD

**Issue by jglukasik** [aaronpk/Overland-iOS#81]
Under the "API" heading at https://overland.p3k.app , the HTTP request made by the app is shown. The `coordinates` field is different than what the app actually sends.  The website shows:

```
        "coordinates": {
          "latitude": 37.331800,
          "longitude": -122.030581
        }
```

The app sends (and the README.md here on Github correctly shows):
```
        "coordinates": [
          -122.030581, 
          37.331800
        ]
```

Just wanted to point this out, so others wouldn't stumble over it too :slightly_smiling_face: 

Thank you for making this app! It is exactly what i was looking for

**Comment by aaronpk** [comment]
Thank you, the docs are updated now.
