### ISSUE TITLE
Configuring AWS API Gateway as Endpoint

### ISSUE THREAD

**Issue by noahmacdonald** [aaronpk/Overland-iOS#82]
I'm having trouble getting the app to connect to my endpoint on the AWS API Gateway. I have the gateway sending the POST to a Lambda function and doing other stuff... But having trouble getting API Gateway to recognize the push from the app. 

Any help is appreciated... Total noob. Thanks.

**Comment by aaronpk** [comment]
You might find this slide deck helpful, @cleverdevil outlines how he got Overland working with AWS: https://cleverdevil.io/s/dlag1GnFrU.pdf I'm not sure if there's a video of it anywhere.
