### ISSUE TITLE
Response Documentation

### ISSUE THREAD

**Issue by chrisbergr** [aaronpk/Overland-iOS#85]
I'm trying to build my own endpoint. At this point, it's still very simple because I want to find out first what I'm receiving there.

		header( 'Content-type:application/json;charset=utf-8' );

		$raw_data = file_get_contents( "php://input" );
		$json_data = json_decode( $raw_data );

		$fp = fopen( 'uploads/location/' . time() . '.json', 'w' );
		fwrite( $fp, $json_data );
		fclose( $fp );

		$data = [
			'result' => 'ok'
		];
		$data_json = json_encode( $data, JSON_PRETTY_PRINT );
		$response->getBody()->write( $data_json );

		return $response;

You write in the documentation that my server should return '"result": "ok"', so I expect the code to work. But Overland always displays the message 'HTTP Error - The data couldn't be read because it isn't in the correct format.'

If I debug via cURL, it looks exactly like described. 

Is the documentation incomplete or is it my fault?

**Comment by aaronpk** [comment]
This looks mostly right. I don't remember how picky the HTTP client in Overland is, but technically your content type header is incorrect. "application/json" already implies utf-8 so that's redundant. Try sending this header instead:

```
Content-type: application/json
```

**Comment by aaronpk** [comment]
The framework you're using might also have its own way to set HTTP headers so it's probably better to use that than the header function as well.

**Comment by chrisbergr** [comment]
You're right, I can use `return $response->withAddedHeader('content-type', 'application/json')->withStatus(200);`

But then I receive the message that the data is in wrong format text/html. cURL says it is `[content_type] => application/json`

Removing the charset doesn't change anything.

**Comment by aaronpk** [comment]
Are you sure your code is actually successfully returning that JSON response to Overland? One way this might be failing is the web server doesn't have permission to write to that folder, or the `uploads/location` folder doesn't exist. In that case, PHP would be showing an error, and not setting the content type to json.

**Comment by chrisbergr** [comment]
Yes, folder exist and permissions are set.

I'm testing this with the following code and always get the files written as expected.

	$raw = '{
	  "locations": [...(json block as seen on https://overland.p3k.app/)...]
	}';

	$data = json_encode($raw);

	$curl = curl_init("https://malture.de/receiver/overland/");
	//$curl = curl_init("http://explorer.localhost/receiver/overland/");
	curl_setopt($curl, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));
	curl_setopt($curl, CURLOPT_POST, true);
	curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
	curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
	$result = curl_exec($curl);
	$responseInfo = curl_getinfo($curl);
	curl_close($curl);

	print_r($result . "\n\r");
	print_r($responseInfo);

**Comment by chrisbergr** [comment]
To be honest, I don't know what happened.

I changed fopen, fwrite and fclose to file_put_contents( $filename, $json_data ); and resolved the errors by the app. Then I realized that I save empty files because the use of json_decode on the received data.

Now it works.

So yes, the documentation describes everything it needs and the fault was on my side.

Thank you for your (fast) support.
