### ISSUE TITLE
Add Southwest as a data source

### ISSUE THREAD

**Issue by dshanske** [aaronpk/Overland-iOS#88]
Easy json query..

https://gist.github.com/dshanske/ef3b85f20d34ac6849616655d7dd100b#file-gistfile1-txt

http://getconnected.southwestwifi.com/current.json

**Comment by aaronpk** [comment]
I've decided to drop this feature from the app as it's going to be too much work to maintain and would be better done as an external service anyway. I was noticing that the takeoff and landings would often not be recorded because the passenger wifi would be disabled below 10,000 feet anyway.
