### ISSUE TITLE
Add Aer Lingus/Panasonic Avionic as a data source

### ISSUE THREAD

**Issue by dshanske** [aaronpk/Overland-iOS#91]
https://gist.github.com/dshanske/91350f141a091d403d5c667fd003ec3d#file-gistfile1-txt

Enjoy https://services.inflightpanasonic.aero/inflight/services/flightdata/v2/flightdata

**Comment by aaronpk** [comment]
I've decided to drop this feature from the app as it's going to be too much work to maintain and would be better done as an external service anyway. I was noticing that the takeoff and landings would often not be recorded because the passenger wifi would be disabled below 10,000 feet anyway.
