### ISSUE TITLE
Add Support for Austrian Airlines Data

### ISSUE THREAD

**Issue by RosemaryOrchard** [aaronpk/Overland-iOS#92]
It would be great if Overland hooked into Austrian Airlines data too!

Source: https://www.austrian-flynet.com/fapi/flightData

Sample: 
```
{"lon":"16.566525","lat":"48.126640","groundSpeed":5,"heading":"-154.8","internetAvailable":false,"aircraftType":"A320","aircraftRegistration":"OE-LBQ","elapsedFlightTime":"00:15","orig":{"lon":13.287711,"lat":52.559686,"code":"TXL","localTime":"2019-11-22T09:08:14"},"dest":{"localTimeAtArrival":"2019-11-22T09:08:22","lon":16.569722,"lat":48.110278,"code":"VIE","localTime":"2019-11-22T09:08:14"},"timeDest":"00:00","distDest":"1.0","altitude":590,"temperature":10,"flightNumber":"","clearRoute":false,"displayProjectedPath":false,"utc":"2019-11-22T08:08:14","displayPA":false,"arincAvailable":true}
```

**Comment by aaronpk** [comment]
I've decided to drop this feature from the app as it's going to be too much work to maintain and would be better done as an external service anyway. I was noticing that the takeoff and landings would often not be recorded because the passenger wifi would be disabled below 10,000 feet anyway.
