### ISSUE TITLE
Supporting two-way communication

### ISSUE THREAD

**Issue by banzy** [aaronpk/Overland-iOS#94]
Using the JSON response from the custom server, currently { result: "ok" } for introducing new values in the app. For instance, setting a geofencing area or changing the tracking times remotely.  Something like: 
{  result:"ok",
   set:{  
      tracking:5,
      geof:{ mode":"out", center:[ 39.12, 0.28 ]}
   } 
}

**Comment by njkleiner** [comment]
It would be cool if Overland supported loading settings from a remote URL similar to [Micropub configuration queries](https://www.w3.org/TR/micropub/#configuration).

**Comment by aaronpk** [comment]
This is done now! Check out the readme for details!

https://github.com/aaronpk/Overland-iOS?tab=readme-ov-file#configuration-by-server-response
