### ISSUE TITLE
Include battery levels for connected devices

### ISSUE THREAD

**Issue by ehershey** [aaronpk/Overland-iOS#95]
One unexpected feature I love in the app is having my phone battery level kept up to date somewhere off of my phone so I can check it without touching my phone or necessarily being near it. I'd love to also include connected device battery levels like bluetooth headphones, keyboards and mice, and smart battery cases.

**Comment by aaronpk** [comment]
That's a great idea!

I have no idea if the iOS APIs provide access to that information but it's worth looking into!

**Comment by aaronpk** [comment]
I did some digging and I don't see any way that this is possible, sorry!
