### ISSUE TITLE
background sending data

### ISSUE THREAD

**Issue by pete111** [aaronpk/Overland-iOS#98]
Hi, this is not the issue, but just a question.
How your app works when in background?

I need to have app running in background and it should send gps location to my server periodically every 1 or 3 or 5 minutes. Is it possible please?

**Comment by lostfocus** [comment]
You're in luck: that's exactly what this app does.

**Comment by pete111** [comment]
> You're in luck: that's exactly what this app does.

perferct thank you.
I heard about some restrictions on ios when app runs in background... so if it is ok for this type of usage. Also I did not see at app snapshot in app store if there is option to set "hard" time period for updates. So just to be sure if it is possible :) (to prevent high battery drain - for me it is perfectly ok when I get just one position on my server per 1/3/5 minutes)

P.S. sorry for my stupid question, but I am not ios user :) Just need it for one our ios and I am not familiar with it and restrictions about Ios system :) So I am asking stupid questions :D

**Comment by aaronpk** [comment]
There isn't a way for apps to request specific intervals, but it will attempt to send at roughly the interval set in the app. Nothing about location services on iOS is an exact science, but this app is my best attempt at wrangling control over location tracking from iOS.
